modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/IAFEnvoy/IceAndFire-CE/issues"
license = "LGPL-3.0"

[[mods]]
modId = "iceandfire"
version = "${version}"
displayName = "Ice And Fire CE"
authors = "Alexthe666 (Origin Author), IAFEnvoy"
description = '''
An unofficial fork of Ice And Fire.
Dragons and other mythological creatures in minecraft.
'''
#logoFile = ""

[[dependencies.iceandfire]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfire]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfire]]
modId = "uranus"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfire]]
modId = "jupiter"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"